image: rust:1.80.0

stages:
  - prepare
  - build
  - test
  - doc

prepare:
  tags:
    - rust-1.80
  cache:
    paths:
      - mosek.lic
      - mosek/10.2/tools/platform/linux64x86
      
  script:
    - curl -O https://download.mosek.com/stable/10.2.3/mosektoolslinuxaarch64.tar.bz2 
    - tar xf mosektoolslinuxaarch64.tar.bz2

build:
  tags:
    - rust-1.80
  cache:
    paths:
      - target/release
      - examples/demos/target/release
  variables:
    MOSEK_INST_BASE: .
  script:
    - cargo build --release
    - cargo build --release --examples
    - (cd examples/demos; cargo build && cargo build --release -p ellipsoids)

test:
  tags:
    - rust-1.80
  variables:
    MOSEK_INST_BASE: .
    MOSEKLM_LICENSE_FILE: $GITLAB_PROJECT_PATH/mosek.lic
    LD_LIBRARY_PATH: mosek/10.2/tools/platform/linux64x86/bin
  script:
    - curl -o mosek.lic http://files.mosek.intranet/docs/lic/mosek11-1.lic
    - cargo test --release
    - cargo test --release --examples 
    - (cd examples/demos; cargo test --release && cargo test --release -p ellipsoids)

doc:
  tags:
    - rust-1.80
  script:
    - cargo doc --release
    - tar cjvf doc.tar.bz2 -C target doc
  artifacts:
    paths: 
      - doc.tar.bz2
  

