[package]
name = "mosekmodel"
version = "0.1.0"
edition = "2021"
rust-version = "1.69.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
mosek = "10.2"

[dev-dependencies]
criterion = "0.3"
#bencher = "0.1"

[[bench]]
name="performance"
harness = false

[[example]]
name = "eval"
crate-type = ["cdylib"]

[[example]]
name = "nearestcorr"
crate-type = ["cdylib"]

