        [package]
name = "mosekmodel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mosek = "10.0"
itertools = "0.10"

[dev-dependencies]
#Criterion = "0.3"
bencher = "0.1"

[[bench]]
name="performance"
harness = false
