[package]
name = "mosekmodel"
version = "0.1.0"
edition = "2021"
rust-version = "1.69.0"
description = "Library for conic optimization modeling with Mosek"
authors = [ "Ulf Worsøe <ulf.worsoe@mosek.com>" ]
keywords = ["mosek","optimization","conic_optimization","linear_optimization","integer_optimization","conic_modeling"]
categories = ["mathematics","science"]
# licence = 
# repository =
# documentation = 
# homepage =
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["utils"]

[dependencies]
itertools = "0.10"
mosek = "10.2"
rand_distr = "0.4.3"
utils = { path = "utils" }
#mosek = { path = "../Mosek.rust" }

[dev-dependencies]
criterion = { version = "0.5.1", features = [ "html_reports" ] }
rand = "0.8.5"
#bencher = "0.1"

#[[bench]]
#name="performance"
#harness = false

[[bench]]
name="exprs"
harness = false

[[example]]
name = "eval"
crate-type = ["cdylib"]

#[[example]]
#name = "nearestcorr"
#crate-type = ["cdylib"]

