[package]
name = "truss"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = "0.19.4"
gtk = { version = "0.8.0", package = "gtk4", features = ["v4_6"] }
itertools = "0.13.0"
mosekcomodel = "0.4.1"
mosekcomodel_mosek = "0.4.0"
mosek = "11.0"
