[package]
name = "whales"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = "0.19.4"
gtk = { version = "0.8.0", package = "gtk4", features = ["v4_6"] }
mosekmodel = { version = "0.1.0", path = "../.." }
