[package]
name = "tsp"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
mosekcomodel = { version = "0.1.1", path = "../../.." }
rand = "0.9.0"
gtk = { version = "0.8.0", package = "gtk4", features = ["v4_6"] }
cairo-rs = "0.19.4"
