[package]
name = "optserver"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
mosekcomodel = { version = "0.3.0", path = "../../.." }
mosekcomodel_mosek = "0.1.0"
ureq = "3.0.11"

[lib]
