name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get MOSEK
      run: curl -o mosektoolslinux64x86.tar.bz2 https://download.mosek.com/stable/11.0.27/mosektoolslinux64x86.tar.bz2 && tar xf mosektoolslinux64x86.tar.bz2
    - name: Build
      run: MOSEK_BINDIR_110=mosek/11.0/tools/platform/linux64x86/bin cargo build --all --verbose
    - name: Run tests
      run: mkdir -p ~/mosek && echo "${{secrets.LICENSE}}" > ~/mosek/mosek.lic && LD_LIBRARY_PATH=mosek/11.0/tools/platform/linux64x86/bin cargo test --all --verbose
